"""s06_rfq_author"""
from alembic import op
import sqlalchemy as sa

revision = '07985afd7ae7'
down_revision = '4b7dc5a480e4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_requests', sa.Column('author_id', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'supplier_requests', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'supplier_requests', type_='foreignkey')
    op.drop_column('supplier_requests', 'author_id')
    # ### end Alembic commands ###
