"""s06_quote_attachments"""
import sqlalchemy as sa

from alembic import op

revision = '1d28538f5e8f'
down_revision = '07985afd7ae7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('attachments', sa.JSON(), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'attachments')
    # ### end Alembic commands ###
