"""remove previous_id unique constraint"""
from alembic import op
import sqlalchemy as sa

revision = '1ea5852eaf70'
down_revision = '1d28538f5e8f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('quotes_previous_id_key'), 'quotes', type_='unique')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('quotes_previous_id_key'), 'quotes', ['previous_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
