"""initial_schema"""

import sqlalchemy as sa

from alembic import op

revision = "2abdec759d06"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_attempts",
        sa.Column("identity", sa.String(length=254), nullable=False),
        sa.Column("ip", sa.String(length=100), nullable=False),
        sa.Column("successful", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_login_attempts_identity"), "login_attempts", ["identity"], unique=False)
    op.create_index(op.f("ix_login_attempts_ip"), "login_attempts", ["ip"], unique=False)
    op.create_table(
        "manufacturers",
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("normalized_name", sa.String(length=250), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("normalized_name"),
    )
    op.create_table(
        "outbox_events",
        sa.Column("event_key", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_key"),
    )
    op.create_index(op.f("ix_outbox_events_status"), "outbox_events", ["status"], unique=False)
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "sellers",
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "substances",
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("cas", sa.String(length=20), nullable=True),
        sa.Column("no_cas_reason", sa.Text(), nullable=False),
        sa.Column("synonyms", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cas"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("mfa_secret", sa.Text(), nullable=True),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("mfa_last_step", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "audit_events",
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_actor_id"), "audit_events", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_events_entity_id"), "audit_events", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_events_entity_type"), "audit_events", ["entity_type"], unique=False)
    op.create_index(op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False)
    op.create_table(
        "auth_sessions",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "calculation_profiles",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("previous_id", sa.String(length=36), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_until", sa.Date(), nullable=True),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_id"],
            ["calculation_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "counterparties",
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("tax_id", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("phone", sa.String(length=100), nullable=True),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("external_id", sa.String(length=250), nullable=True),
        sa.Column("source", sa.String(length=250), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_index(op.f("ix_counterparties_email"), "counterparties", ["email"], unique=False)
    op.create_index(op.f("ix_counterparties_name"), "counterparties", ["name"], unique=False)
    op.create_index(op.f("ix_counterparties_owner_id"), "counterparties", ["owner_id"], unique=False)
    op.create_index(op.f("ix_counterparties_phone"), "counterparties", ["phone"], unique=False)
    op.create_index(op.f("ix_counterparties_tax_id"), "counterparties", ["tax_id"], unique=False)
    op.create_table(
        "idempotency_records",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "scope", "key"),
    )
    op.create_table(
        "import_batches",
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("source_name", sa.String(length=250), nullable=False),
        sa.Column("file_key", sa.String(length=250), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("mapping", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_import_batches_author_id"), "import_batches", ["author_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("event_key", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "event_key"),
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "permission_grants",
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("role_id", sa.String(length=36), nullable=True),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("scope", sa.String(length=10), nullable=False),
        sa.Column("allow", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("(user_id IS NULL) <> (role_id IS NULL)"),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permission_grants_code"), "permission_grants", ["code"], unique=False)
    op.create_index(op.f("ix_permission_grants_role_id"), "permission_grants", ["role_id"], unique=False)
    op.create_index(op.f("ix_permission_grants_user_id"), "permission_grants", ["user_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("substance_id", sa.String(length=36), nullable=False),
        sa.Column("manufacturer_id", sa.String(length=36), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("article", sa.String(length=150), nullable=False),
        sa.Column("purity", sa.String(length=200), nullable=False),
        sa.Column("packaging", sa.String(length=200), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("package_quantity", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verification_reason", sa.Text(), nullable=False),
        sa.Column("specification", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["manufacturer_id"],
            ["manufacturers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["substance_id"],
            ["substances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint"),
    )
    op.create_table(
        "tasks",
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=True),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("assignee_id", sa.String(length=36), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_key", sa.String(length=200), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_key"),
    )
    op.create_index(op.f("ix_tasks_assignee_id"), "tasks", ["assignee_id"], unique=False)
    op.create_index(op.f("ix_tasks_due_at"), "tasks", ["due_at"], unique=False)
    op.create_index(op.f("ix_tasks_entity_id"), "tasks", ["entity_id"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id"),
    )
    op.create_index(op.f("ix_user_roles_role_id"), "user_roles", ["role_id"], unique=False)
    op.create_index(op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False)
    op.create_table(
        "waves",
        sa.Column("number", sa.String(length=80), nullable=False),
        sa.Column("route", sa.String(length=300), nullable=False),
        sa.Column("origin_country", sa.String(length=100), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("close_date", sa.Date(), nullable=False),
        sa.Column("departure_date", sa.Date(), nullable=False),
        sa.Column("arrival_date", sa.Date(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    op.create_table(
        "contacts",
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("position", sa.String(length=200), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("phone", sa.String(length=100), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["counterparties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contacts_client_id"), "contacts", ["client_id"], unique=False)
    op.create_table(
        "import_rows",
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("candidate_ids", sa.JSON(), nullable=False),
        sa.Column("match_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["import_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["counterparties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "row_number"),
    )
    op.create_index(op.f("ix_import_rows_batch_id"), "import_rows", ["batch_id"], unique=False)
    op.create_table(
        "calls",
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("contact_id", sa.String(length=36), nullable=True),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("result", sa.String(length=60), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("next_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["counterparties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], use_alter=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_calls_author_id"), "calls", ["author_id"], unique=False)
    op.create_index(op.f("ix_calls_client_id"), "calls", ["client_id"], unique=False)
    op.create_table(
        "requests",
        sa.Column("number", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("seller_id", sa.String(length=36), nullable=True),
        sa.Column("contact_id", sa.String(length=36), nullable=True),
        sa.Column("source_call_id", sa.String(length=36), nullable=True),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("commercial_stage", sa.String(length=50), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("loss_reason", sa.Text(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sale_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_test", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["counterparties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["sellers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_call_id"],
            ["calls.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    op.create_index(op.f("ix_requests_client_id"), "requests", ["client_id"], unique=False)
    op.create_index(op.f("ix_requests_closed_at"), "requests", ["closed_at"], unique=False)
    op.create_index(op.f("ix_requests_commercial_stage"), "requests", ["commercial_stage"], unique=False)
    op.create_index(op.f("ix_requests_owner_id"), "requests", ["owner_id"], unique=False)
    op.create_index(op.f("ix_requests_sale_confirmed_at"), "requests", ["sale_confirmed_at"], unique=False)
    op.create_index(op.f("ix_requests_title"), "requests", ["title"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("submitted_by", sa.String(length=36), nullable=False),
        sa.Column("reviewer_id", sa.String(length=36), nullable=False),
        sa.Column("decided_by", sa.String(length=36), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_approvals_request_id"), "approvals", ["request_id"], unique=False)
    op.create_table(
        "calculations",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("previous_id", sa.String(length=36), nullable=True),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_id"],
            ["calculations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["calculation_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_calculations_request_id"), "calculations", ["request_id"], unique=False)
    op.create_table(
        "chats",
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=True),
        sa.Column("wave_id", sa.String(length=36), nullable=True),
        sa.Column("direct_key", sa.String(length=80), nullable=True),
        sa.Column("last_sequence", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(kind = 'request' AND request_id IS NOT NULL AND wave_id IS NULL) OR (kind = 'wave' AND wave_id IS NOT NULL AND request_id IS NULL) OR (kind IN ('direct','group') AND request_id IS NULL AND wave_id IS NULL)"
        ),
        sa.CheckConstraint("kind IN ('direct','group','request','wave')"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wave_id"],
            ["waves.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("direct_key"),
    )
    op.create_index(op.f("ix_chats_owner_id"), "chats", ["owner_id"], unique=False)
    op.create_index(op.f("ix_chats_request_id"), "chats", ["request_id"], unique=False)
    op.create_index(op.f("ix_chats_wave_id"), "chats", ["wave_id"], unique=False)
    op.create_table(
        "request_items",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("cas", sa.String(length=30), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("unit", sa.String(length=30), nullable=True),
        sa.Column("purity", sa.String(length=200), nullable=True),
        sa.Column("packaging", sa.String(length=200), nullable=True),
        sa.Column("allow_analogue", sa.Boolean(), nullable=False),
        sa.Column("desired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("quantity IS NULL OR quantity > 0"),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_request_items_request_id"), "request_items", ["request_id"], unique=False)
    op.create_table(
        "request_members",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id", "user_id"),
    )
    op.create_index(op.f("ix_request_members_request_id"), "request_members", ["request_id"], unique=False)
    op.create_index(op.f("ix_request_members_user_id"), "request_members", ["user_id"], unique=False)
    op.create_table(
        "supplier_requests",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("supplier_id", sa.String(length=36), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("file_key", sa.String(length=300), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_channel", sa.String(length=200), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["supplier_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["counterparties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_supplier_requests_request_id"), "supplier_requests", ["request_id"], unique=False
    )
    op.create_table(
        "chat_members",
        sa.Column("chat_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("read_sequence", sa.Integer(), nullable=False),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("read_sequence >= 0"),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "user_id"),
    )
    op.create_index(op.f("ix_chat_members_chat_id"), "chat_members", ["chat_id"], unique=False)
    op.create_index(op.f("ix_chat_members_user_id"), "chat_members", ["user_id"], unique=False)
    op.create_table(
        "commercial_documents",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("seller_id", sa.String(length=36), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("number", sa.String(length=80), nullable=False),
        sa.Column("calculation_id", sa.String(length=36), nullable=False),
        sa.Column("proposal_id", sa.String(length=36), nullable=True),
        sa.Column("previous_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("files", sa.JSON(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_channel", sa.String(length=200), nullable=True),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("total >= 0"),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["calculation_id"],
            ["calculations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["counterparties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_id"],
            ["commercial_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["commercial_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["sellers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("seller_id", "kind", "number"),
    )
    op.create_index(
        op.f("ix_commercial_documents_request_id"), "commercial_documents", ["request_id"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("chat_id", sa.String(length=36), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("mention_ids", sa.JSON(), nullable=False),
        sa.Column("document_refs", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("sequence > 0"),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "sequence"),
    )
    op.create_index(op.f("ix_messages_author_id"), "messages", ["author_id"], unique=False)
    op.create_index(op.f("ix_messages_chat_id"), "messages", ["chat_id"], unique=False)
    op.create_table(
        "quotes",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("item_revision", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("supplier_id", sa.String(length=36), nullable=False),
        sa.Column("supplier_request_id", sa.String(length=36), nullable=True),
        sa.Column("previous_id", sa.String(length=36), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("price_unit", sa.String(length=20), nullable=False),
        sa.Column("available_quantity", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("minimum_quantity", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("multiple", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("requires_confirmation", sa.Boolean(), nullable=False),
        sa.Column("is_analogue", sa.Boolean(), nullable=False),
        sa.Column("sample", sa.Boolean(), nullable=False),
        sa.Column("terms", sa.JSON(), nullable=False),
        sa.Column("revision_reason", sa.Text(), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "price >= 0 AND available_quantity > 0 AND minimum_quantity >= 0 AND multiple > 0"
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["request_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_id"],
            ["quotes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["counterparties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_request_id"],
            ["supplier_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("previous_id"),
    )
    op.create_index(op.f("ix_quotes_item_id"), "quotes", ["item_id"], unique=False)
    op.create_index(op.f("ix_quotes_request_id"), "quotes", ["request_id"], unique=False)
    op.create_table(
        "request_item_revisions",
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["request_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_id", "revision"),
    )
    op.create_index(
        op.f("ix_request_item_revisions_item_id"), "request_item_revisions", ["item_id"], unique=False
    )
    op.create_table(
        "executions",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("proposal_id", sa.String(length=36), nullable=False),
        sa.Column("quote_id", sa.String(length=36), nullable=False),
        sa.Column("line_id", sa.String(length=80), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("cancelled_quantity", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("acceptance_reason", sa.Text(), nullable=False),
        sa.Column("accepted_by", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("financing_deficit", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("quantity > 0 AND cancelled_quantity >= 0 AND cancelled_quantity <= quantity"),
        sa.ForeignKeyConstraint(
            ["accepted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["request_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["commercial_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_executions_request_id"), "executions", ["request_id"], unique=False)
    op.create_table(
        "files",
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("media_type", sa.String(length=100), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=200), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("classification", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("scan_result", sa.String(length=100), nullable=True),
        sa.Column("scanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("request_id", sa.String(length=36), nullable=True),
        sa.Column("client_id", sa.String(length=36), nullable=True),
        sa.Column("chat_id", sa.String(length=36), nullable=True),
        sa.Column("wave_id", sa.String(length=36), nullable=True),
        sa.Column("quote_id", sa.String(length=36), nullable=True),
        sa.Column("calculation_id", sa.String(length=36), nullable=True),
        sa.Column("document_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("classification IN ('general','purchase','calculation','reward','profit')"),
        sa.CheckConstraint("status IN ('quarantined','clean','infected','scan_failed')"),
        sa.CheckConstraint(
            "(CASE WHEN request_id IS NULL THEN 0 ELSE 1 END + CASE WHEN client_id IS NULL THEN 0 ELSE 1 END + CASE WHEN chat_id IS NULL THEN 0 ELSE 1 END + CASE WHEN wave_id IS NULL THEN 0 ELSE 1 END + CASE WHEN quote_id IS NULL THEN 0 ELSE 1 END + CASE WHEN calculation_id IS NULL THEN 0 ELSE 1 END + CASE WHEN document_id IS NULL THEN 0 ELSE 1 END) = 1"
        ),
        sa.CheckConstraint("size > 0"),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["calculation_id"],
            ["calculations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["counterparties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["commercial_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wave_id"],
            ["waves.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(op.f("ix_files_calculation_id"), "files", ["calculation_id"], unique=False)
    op.create_index(op.f("ix_files_chat_id"), "files", ["chat_id"], unique=False)
    op.create_index(op.f("ix_files_client_id"), "files", ["client_id"], unique=False)
    op.create_index(op.f("ix_files_document_id"), "files", ["document_id"], unique=False)
    op.create_index(op.f("ix_files_quote_id"), "files", ["quote_id"], unique=False)
    op.create_index(op.f("ix_files_request_id"), "files", ["request_id"], unique=False)
    op.create_index(op.f("ix_files_sha256"), "files", ["sha256"], unique=False)
    op.create_index(op.f("ix_files_status"), "files", ["status"], unique=False)
    op.create_index(op.f("ix_files_wave_id"), "files", ["wave_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("seller_id", sa.String(length=36), nullable=False),
        sa.Column("invoice_id", sa.String(length=36), nullable=True),
        sa.Column("amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("number", sa.String(length=200), nullable=False),
        sa.Column("external_id", sa.String(length=250), nullable=True),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("evidence_file_id", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("declared_by", sa.String(length=36), nullable=False),
        sa.Column("confirmed_by", sa.String(length=36), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("amount > 0"),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["counterparties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["declared_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["commercial_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["sellers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("seller_id", "external_id"),
    )
    op.create_index(op.f("ix_payments_request_id"), "payments", ["request_id"], unique=False)
    op.create_table(
        "message_files",
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id", "file_id"),
    )
    op.create_index(op.f("ix_message_files_file_id"), "message_files", ["file_id"], unique=False)
    op.create_index(op.f("ix_message_files_message_id"), "message_files", ["message_id"], unique=False)
    op.create_table(
        "payment_allocations",
        sa.Column("payment_id", sa.String(length=36), nullable=False),
        sa.Column("invoice_id", sa.String(length=36), nullable=False),
        sa.Column("amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("amount > 0"),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["commercial_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_allocations_invoice_id"), "payment_allocations", ["invoice_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_allocations_payment_id"), "payment_allocations", ["payment_id"], unique=False
    )
    op.create_table(
        "wave_allocations",
        sa.Column("wave_id", sa.String(length=36), nullable=False),
        sa.Column("execution_id", sa.String(length=36), nullable=False),
        sa.Column("approval_id", sa.String(length=36), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("previous_id", sa.String(length=36), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("quantity > 0"),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approvals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["executions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_id"],
            ["wave_allocations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wave_id"],
            ["waves.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wave_allocations_execution_id"), "wave_allocations", ["execution_id"], unique=False
    )
    op.create_index(op.f("ix_wave_allocations_wave_id"), "wave_allocations", ["wave_id"], unique=False)
    op.create_table(
        "fulfillment_events",
        sa.Column("allocation_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence_file_id", sa.String(length=80), nullable=True),
        sa.Column("correction_of", sa.String(length=36), nullable=True),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["wave_allocations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["correction_of"],
            ["fulfillment_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fulfillment_events_allocation_id"), "fulfillment_events", ["allocation_id"], unique=False
    )
    op.create_table(
        "payment_reversals",
        sa.Column("payment_id", sa.String(length=36), nullable=False),
        sa.Column("allocation_id", sa.String(length=36), nullable=True),
        sa.Column("amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("amount > 0"),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["payment_allocations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_reversals_payment_id"), "payment_reversals", ["payment_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_reversals_payment_id"), table_name="payment_reversals")
    op.drop_table("payment_reversals")
    op.drop_index(op.f("ix_fulfillment_events_allocation_id"), table_name="fulfillment_events")
    op.drop_table("fulfillment_events")
    op.drop_index(op.f("ix_wave_allocations_wave_id"), table_name="wave_allocations")
    op.drop_index(op.f("ix_wave_allocations_execution_id"), table_name="wave_allocations")
    op.drop_table("wave_allocations")
    op.drop_index(op.f("ix_payment_allocations_payment_id"), table_name="payment_allocations")
    op.drop_index(op.f("ix_payment_allocations_invoice_id"), table_name="payment_allocations")
    op.drop_table("payment_allocations")
    op.drop_index(op.f("ix_message_files_message_id"), table_name="message_files")
    op.drop_index(op.f("ix_message_files_file_id"), table_name="message_files")
    op.drop_table("message_files")
    op.drop_index(op.f("ix_payments_request_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_files_wave_id"), table_name="files")
    op.drop_index(op.f("ix_files_status"), table_name="files")
    op.drop_index(op.f("ix_files_sha256"), table_name="files")
    op.drop_index(op.f("ix_files_request_id"), table_name="files")
    op.drop_index(op.f("ix_files_quote_id"), table_name="files")
    op.drop_index(op.f("ix_files_document_id"), table_name="files")
    op.drop_index(op.f("ix_files_client_id"), table_name="files")
    op.drop_index(op.f("ix_files_chat_id"), table_name="files")
    op.drop_index(op.f("ix_files_calculation_id"), table_name="files")
    op.drop_table("files")
    op.drop_index(op.f("ix_executions_request_id"), table_name="executions")
    op.drop_table("executions")
    op.drop_index(op.f("ix_request_item_revisions_item_id"), table_name="request_item_revisions")
    op.drop_table("request_item_revisions")
    op.drop_index(op.f("ix_quotes_request_id"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_item_id"), table_name="quotes")
    op.drop_table("quotes")
    op.drop_index(op.f("ix_messages_chat_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_author_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_commercial_documents_request_id"), table_name="commercial_documents")
    op.drop_table("commercial_documents")
    op.drop_index(op.f("ix_chat_members_user_id"), table_name="chat_members")
    op.drop_index(op.f("ix_chat_members_chat_id"), table_name="chat_members")
    op.drop_table("chat_members")
    op.drop_index(op.f("ix_supplier_requests_request_id"), table_name="supplier_requests")
    op.drop_table("supplier_requests")
    op.drop_index(op.f("ix_request_members_user_id"), table_name="request_members")
    op.drop_index(op.f("ix_request_members_request_id"), table_name="request_members")
    op.drop_table("request_members")
    op.drop_index(op.f("ix_request_items_request_id"), table_name="request_items")
    op.drop_table("request_items")
    op.drop_index(op.f("ix_chats_wave_id"), table_name="chats")
    op.drop_index(op.f("ix_chats_request_id"), table_name="chats")
    op.drop_index(op.f("ix_chats_owner_id"), table_name="chats")
    op.drop_table("chats")
    op.drop_index(op.f("ix_calculations_request_id"), table_name="calculations")
    op.drop_table("calculations")
    op.drop_index(op.f("ix_approvals_request_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_requests_title"), table_name="requests")
    op.drop_index(op.f("ix_requests_sale_confirmed_at"), table_name="requests")
    op.drop_index(op.f("ix_requests_owner_id"), table_name="requests")
    op.drop_index(op.f("ix_requests_commercial_stage"), table_name="requests")
    op.drop_index(op.f("ix_requests_closed_at"), table_name="requests")
    op.drop_index(op.f("ix_requests_client_id"), table_name="requests")
    op.drop_table("requests")
    op.drop_index(op.f("ix_calls_client_id"), table_name="calls")
    op.drop_index(op.f("ix_calls_author_id"), table_name="calls")
    op.drop_table("calls")
    op.drop_index(op.f("ix_import_rows_batch_id"), table_name="import_rows")
    op.drop_table("import_rows")
    op.drop_index(op.f("ix_contacts_client_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_table("waves")
    op.drop_index(op.f("ix_user_roles_user_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_role_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_entity_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_due_at"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_assignee_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("products")
    op.drop_index(op.f("ix_permission_grants_user_id"), table_name="permission_grants")
    op.drop_index(op.f("ix_permission_grants_role_id"), table_name="permission_grants")
    op.drop_index(op.f("ix_permission_grants_code"), table_name="permission_grants")
    op.drop_table("permission_grants")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_import_batches_author_id"), table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_table("idempotency_records")
    op.drop_index(op.f("ix_counterparties_tax_id"), table_name="counterparties")
    op.drop_index(op.f("ix_counterparties_phone"), table_name="counterparties")
    op.drop_index(op.f("ix_counterparties_owner_id"), table_name="counterparties")
    op.drop_index(op.f("ix_counterparties_name"), table_name="counterparties")
    op.drop_index(op.f("ix_counterparties_email"), table_name="counterparties")
    op.drop_table("counterparties")
    op.drop_table("calculation_profiles")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("app_settings")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("substances")
    op.drop_table("sellers")
    op.drop_table("roles")
    op.drop_index(op.f("ix_outbox_events_status"), table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_table("manufacturers")
    op.drop_index(op.f("ix_login_attempts_ip"), table_name="login_attempts")
    op.drop_index(op.f("ix_login_attempts_identity"), table_name="login_attempts")
    op.drop_table("login_attempts")
    # ### end Alembic commands ###
