"""s04_settings_versions"""
from alembic import op
import sqlalchemy as sa

revision = '4b7dc5a480e4'
down_revision = '7b8bc7a449f9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'))
    op.add_column('app_settings', sa.Column('previous_id', sa.String(length=36), nullable=True))
    op.add_column('app_settings', sa.Column('effective_from', sa.Date(), nullable=False, server_default=sa.text('CURRENT_DATE')))
    op.add_column('app_settings', sa.Column('effective_until', sa.Date(), nullable=True))
    op.add_column('app_settings', sa.Column('reason', sa.Text(), nullable=True))
    op.drop_constraint('app_settings_key_key', 'app_settings', type_='unique')
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=False)
    op.create_foreign_key('fk_app_settings_previous_id', 'app_settings', 'app_settings', ['previous_id'], ['id'])
    op.add_column('calculation_profiles', sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calculation_profiles', 'status')
    op.drop_constraint('fk_app_settings_previous_id', 'app_settings', type_='foreignkey')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.create_unique_constraint('app_settings_key_key', 'app_settings', ['key'])
    op.drop_column('app_settings', 'reason')
    op.drop_column('app_settings', 'effective_until')
    op.drop_column('app_settings', 'effective_from')
    op.drop_column('app_settings', 'previous_id')
    op.drop_column('app_settings', 'status')
    # ### end Alembic commands ###
