"""Add missing constraints"""

from alembic import op

revision = '7b8bc7a449f9'
down_revision = '51eab019a784'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_calls_task_id_tasks', 'calls', 'tasks', ['task_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_calls_task_id_tasks', 'calls', type_='foreignkey')
    # ### end Alembic commands ###
