-- Create API/Worker Role (Runtime)
CREATE ROLE crm_api WITH LOGIN PASSWORD 'crm_api_password';

-- Create Backup Role
CREATE ROLE crm_backup WITH LOGIN PASSWORD 'crm_backup_password';

\c crm

-- Grant API Role privileges (DML only)
GRANT USAGE ON SCHEMA public TO crm_api;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO crm_api;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO crm_api;

GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO crm_api;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO crm_api;

-- Grant Backup Role privileges (SELECT only)
GRANT USAGE ON SCHEMA public TO crm_backup;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO crm_backup;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO crm_backup;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO crm_backup;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO crm_backup;
